// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuveszetiGaleriaApi.Context;

#nullable disable

namespace MuveszetiGaleriaApi.Migrations
{
    [DbContext(typeof(MuveszContext))]
    partial class MuveszContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MuveszetiGaleriaApi.Entities.Kiallitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Felelos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kiallitasok");
                });

            modelBuilder.Entity("MuveszetiGaleriaApi.Entities.Mualkotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KiallitasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuveszId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KiallitasId");

                    b.HasIndex("MuveszId");

                    b.ToTable("Mualkotasok");
                });

            modelBuilder.Entity("MuveszetiGaleriaApi.Entities.Muvesz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Muveszek");
                });

            modelBuilder.Entity("MuveszetiGaleriaApi.Entities.Mualkotas", b =>
                {
                    b.HasOne("MuveszetiGaleriaApi.Entities.Kiallitas", "Kiallitas")
                        .WithMany()
                        .HasForeignKey("KiallitasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuveszetiGaleriaApi.Entities.Muvesz", "Muvesz")
                        .WithMany()
                        .HasForeignKey("MuveszId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiallitas");

                    b.Navigation("Muvesz");
                });
#pragma warning restore 612, 618
        }
    }
}
